backend:
  name: git-gateway
  repo: pavel-sheremet-dev/gw-bb-project
  branch: dev
media_folder: static/assets
public_folder: /assets
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: gw-bb-project
    api_key: 332238787687881
    default_transformations:
      - - fetch_format: auto
          quality: auto
          crop: scale
collections:
  # Main page model
  - label: 'Page'
    name: 'page'
    folder: 'cmsdata/main'
    slug: '{{groupId}}-{{language}}'
    create: false # ограничение на создание документа
    delete: false # ограничение на удаление документа
    fields:
      - {
          label: 'Group identifier',
          name: 'groupId',
          widget: 'hidden',
          default: 'main',
        }
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' } # hidden прячет поле в СMS
      - {
          label: 'Title',
          name: 'title',
          widget: 'hidden',
          default: 'Main Page',
        }
      - { label: 'Update Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - { label: 'Image', name: 'imageUrl', widget: 'image', required: false }
  # Policy list model
  - label: 'Policy'
    name: 'policy'
    folder: 'cmsdata/policy'
    slug: '{{policyId}}-{{title}}'
    create: true # ограничение на создание документа
    fields:
      - {
          label: 'Policy identifier',
          name: 'policyId',
          widget: 'hidden',
          default: 'policy',
        }
      - { label: 'Update Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'number', value_type: 'float' }
      - { label: 'Description [UK]', name: 'uk' }
      - { label: 'Description [RU]', name: 'ru' }
      - { label: 'Description [EN]', name: 'en' }
      - {
          label: 'Notes',
          name: 'body',
          widget: 'markdown',
          required: false,
          default: 'These markings are not displayed on the site',
        }
