backend:
  name: git-gateway
  repo: GoWeb-Internship/gw-bb-project
  branch: dev
media_folder: static/assets
public_folder: /assets
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: gw-bb-project
    api_key: 332238787687881
    default_transformations:
      - - fetch_format: auto
          quality: auto
          crop: scale
collections:
  # Main page model
  - label: 'Page'
    name: 'page'
    folder: 'cmsdata/main'
    slug: '{{fieldIdName}}-{{language}}'
    create: false # ограничение на создание документа
    delete: false # ограничение на удаление документа
    identifier_field: title
    fields:
      - {
          label: 'Group identifier',
          name: 'fieldIdName',
          widget: 'hidden',
          default: 'main',
        }
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' } # hidden прячет поле в СMS
      - {
          label: 'Title',
          name: 'title',
          widget: 'hidden',
          default: 'Main Page',
        }
      - { label: 'Update Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - { label: 'Image', name: 'imageUrl', widget: 'image', required: false }
  # Policy list model
  - label: 'Policy'
    name: 'policy'
    folder: 'cmsdata/policy'
    slug: '{{fieldIdName}}-{{title}}'
    identifier_field: title
    create: true # ограничение на создание документа
    fields:
      - {
          label: 'Policy identifier',
          name: 'fieldIdName',
          widget: 'hidden',
          default: 'policy',
        }
      - { label: 'Update Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Item number',
          name: 'title',
          widget: 'number',
          value_type: 'float',
        }
      - { label: 'Description [UK]', name: 'uk' }
      - { label: 'Description [RU]', name: 'ru' }
      - { label: 'Description [EN]', name: 'en' }
      - {
          label: 'Notes',
          name: 'body',
          widget: 'markdown',
          required: false,
          default: 'These markings are not displayed on the site',
        }
  # Content Images
  - label: 'Content images'
    name: 'contentImages'
    folder: 'cmsdata/images'
    slug: '{{fieldIdName}}-{{title}}'
    identifier_field: title
    create: false
    delete: false
    fields:
      - {
          label: 'Images identifier',
          name: 'fieldIdName',
          widget: 'hidden',
          default: 'content-image',
        }
      - { label: 'Item', name: 'title', widget: 'string' }
      - { label: 'Update Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'imageUrl', widget: 'image' }
      - { label: 'Description [UK]', name: 'uk' }
      - { label: 'Description [RU]', name: 'ru' }
      - { label: 'Description [EN]', name: 'en' }
      - {
          label: 'Notes',
          name: 'body',
          widget: 'markdown',
          required: false,
          default:
            'These markings are not displayed on the site. Description must
            answer question: What is shown in the picture?',
        }
