backend:
  name: git-gateway
  repo: GoWeb-Internship/gw-bb-project
  branch: dev
media_folder: static/assets
public_folder: /assets
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: gw-bb-project
    api_key: 332238787687881
    default_transformations:
      - - fetch_format: auto
          quality: auto
          crop: scale
collections:
  # Main page model
  - label: 'Page'
    name: 'page'
    folder: 'cmsdata/main'
    slug: '{{fieldIdName}}-{{language}}'
    create: false # ограничение на создание документа
    delete: false # ограничение на удаление документа
    identifier_field: title
    fields:
      - {
          label: 'Group identifier',
          name: 'fieldIdName',
          widget: 'hidden',
          default: 'main',
        }
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' } # hidden прячет поле в СMS
      - {
          label: 'Title',
          name: 'title',
          widget: 'hidden',
          default: 'Main Page',
        }
      - { label: 'Update Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Road Map Section Title',
          name: 'roadMapTitle',
          widget: 'string',
        }
      - { label: 'Prices Section Title', name: 'pricesTitle', widget: 'string' }
      - { label: 'Charity', name: 'charity', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - { label: 'Image', name: 'imageUrl', widget: 'image', required: false }
      - { label: 'Sale', name: 'sale', widget: 'string' }
      - { label: 'Cost one session with sale', name: 'cost', widget: 'string' }
  # Policy list model
  - label: 'Policy'
    name: 'policy'
    folder: 'cmsdata/policy'
    slug: '{{fieldIdName}}-{{title}}'
    identifier_field: title
    create: true # ограничение на создание документа
    delete: true
    fields:
      - {
          label: 'Policy identifier',
          name: 'fieldIdName',
          widget: 'hidden',
          default: 'policy',
        }
      - { label: 'Update Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Item number',
          name: 'title',
          widget: 'number',
          value_type: 'float',
        }
      - { label: 'Description [UK]', name: 'uk' }
      - { label: 'Description [RU]', name: 'ru' }
      - { label: 'Description [EN]', name: 'en' }
      - {
          label: 'Notes',
          name: 'body',
          widget: 'markdown',
          required: false,
          default: 'These markings are not displayed on the site',
        }
  # Content Images
  - label: 'Content images'
    name: 'contentImages'
    folder: 'cmsdata/images'
    slug: '{{fieldIdName}}-{{title}}'
    identifier_field: title
    create: false
    delete: false
    fields:
      - {
          label: 'Images identifier',
          name: 'fieldIdName',
          widget: 'hidden',
          default: 'content-image',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Update Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'imageUrl', widget: 'image' }
      - { label: 'Description [UK]', name: 'uk' }
      - { label: 'Description [RU]', name: 'ru' }
      - { label: 'Description [EN]', name: 'en' }
      - {
          label: 'Notes',
          name: 'body',
          widget: 'markdown',
          required: false,
          default:
            'These markings are not displayed on the site. Description must
            answer question: What is shown in the picture?',
        }
  # Price cards model
  - label: 'Prices Cards'
    name: 'pricesCards'
    folder: 'cmsdata/prices'
    slug: '{{fieldIdName}}-{{title}}'
    identifier_field: title
    create: false
    delete: false
    fields:
      - {
          label: 'Prices identifier',
          name: 'fieldIdName',
          widget: 'hidden',
          default: 'prices',
        }
      - { label: 'Title', name: 'title', widget: 'hidden' }
      - { label: 'ID', name: 'id', widget: 'hidden' }
      - { label: 'Update Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Most recommended',
          name: 'recommended',
          widget: boolean,
          default: false,
        }
      - { label: 'Price, $', name: 'price', widget: 'number' }
      - { label: 'Discount, $', name: 'discount', widget: 'number' }
      - { label: 'Name [UK]', name: 'uk', widget: string }
      - { label: 'Amount of month [UK]', name: 'ukMonth', widget: string }
      - { label: 'Amount of sessions [UK]', name: 'ukSessions', widget: string }
      - { label: 'Name [RU]', name: 'ru', widget: string }
      - { label: 'Amount of month [RU]', name: 'ruMonth', widget: string }
      - { label: 'Amount of sessions [RU]', name: 'ruSessions', widget: string }
      - { label: 'Name [EN]', name: 'en', widget: string }
      - { label: 'Amount of month [EN]', name: 'enMonth', widget: string }
      - { label: 'Amount of sessions [EN]', name: 'enSessions', widget: string }
      - { label: 'Notes', name: 'body', widget: 'markdown', required: false }
  # Road map Steps
  - label: 'Road Map Steps'
    name: 'roadMapSteps'
    folder: 'cmsdata/roadMap'
    slug: '{{fieldIdName}}-{{title}}'
    identifier_field: title
    create: true
    delete: true
    fields:
      - {
          label: 'Road map section identifier',
          name: 'fieldIdName',
          widget: 'hidden',
          default: 'road-map-step',
        }
      - { label: 'Title', name: 'title', widget: 'number' }
      - { label: 'Update Date', name: 'date', widget: 'datetime' }
      - { label: 'Section Title [UK]', name: 'uk', widget: string }
      - { label: 'Section Title [RU]', name: 'ru', widget: string }
      - { label: 'Section Title [EN]', name: 'en', widget: string }
      - { label: 'Notes', name: 'body', widget: 'markdown', required: false }
  # Stories Model
  - label: 'Client stories'
    name: 'stories'
    folder: 'cmsdata/stories'
    slug: '{{fieldIdName}}-{{title}}'
    identifier_field: title
    create: true
    delete: true
    fields:
      - {
          label: 'stories identifier',
          name: 'fieldIdName',
          widget: 'hidden',
          default: 'stories',
        }
      - { label: 'Update Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Name / Position [UK]', name: 'ukName', widget: 'string' }
      - { label: 'Story [UK]', name: 'uk', widget: string }
      - { label: 'Name / Position [RU]', name: 'ruName', widget: 'string' }
      - { label: 'Story [RU]', name: 'ru', widget: string }
      - { label: 'Name / Position [EN]', name: 'enName', widget: 'string' }
      - { label: 'Story [EN]', name: 'en', widget: string }
      - { label: 'Notes', name: 'body', widget: 'markdown', required: false }
  # Feedback Model
  - label: 'Client feedbacks'
    name: 'feedbacks'
    folder: 'cmsdata/feedbacks'
    slug: '{{fieldIdName}}-{{title}}'
    identifier_field: title
    create: true
    delete: true
    fields:
      - {
          label: 'feedbacks identifier',
          name: 'fieldIdName',
          widget: 'hidden',
          default: 'feedbacks',
        }
      - { label: 'Update Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Name / Position [UK]', name: 'ukName', widget: 'string' }
      - { label: 'Story [UK]', name: 'uk', widget: string }
      - { label: 'Name / Position [RU]', name: 'ruName', widget: 'string' }
      - { label: 'Story [RU]', name: 'ru', widget: string }
      - { label: 'Name / Position [EN]', name: 'enName', widget: 'string' }
      - { label: 'Story [EN]', name: 'en', widget: string }
      - { label: 'Avatar', name: 'imageUrl', widget: image }
      - { label: 'Notes', name: 'body', widget: 'markdown', required: false }
      # Offer Model
  - label: 'Offer'
    name: 'offer policy'
    folder: 'cmsdata/offer'
    slug: '{{fieldIdName}}-{{language}}'
    create: false # ограничение на создание документа
    delete: false # ограничение на удаление документа
    identifier_field: title
    fields:
      - {
          label: 'Offer identifier',
          name: 'fieldIdName',
          widget: 'hidden',
          default: 'offer',
        }
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' } # hidden прячет поле в СMS
      - {
          label: 'Title',
          name: 'title',
          widget: 'hidden',
          default: 'Offer Page',
        }
      - { label: 'Update Date', name: 'date', widget: 'datetime' }
      - { label: 'Offer policy title', name: 'offerTitle', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
